# Generated by Django 3.0.6 on 2020-06-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='plannedcourse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='completed_courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='planned_courses',
        ),
        migrations.DeleteModel(
            name='CompletedCourse',
        ),
        migrations.DeleteModel(
            name='PlannedCourse',
        ),
    ]
