# Generated by Django 3.0.6 on 2020-05-12 22:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('course_number', models.IntegerField()),
                ('credits', models.DecimalField(decimal_places=1, max_digits=2)),
                ('countsAsGeneral', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Group')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ManyToManyField(through='school.CourseGroup', to='school.Group'),
        ),
    ]
