# Generated by Django 3.0.6 on 2020-05-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
