# Generated by Django 3.0.6 on 2020-05-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_group_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursegroup',
            unique_together={('group', 'course')},
        ),
    ]
