# Generated by Django 3.0.6 on 2020-05-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_unique_coursegroups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='group',
            new_name='groups',
        ),
    ]
